language: python
python:
  - 3.7.6
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt # install package + test dependencies
script: python manage.py test
